### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by peyman-contribe**
Hi, 
I tried to make it a little bit cleaner and I renamed some variables based on standards and best practices and removed unnecessary codes, parameters and "using".

Btw you need to fix the gitignore to avoid uploading obj and bin folders.

### CODE REVIEW

**Review by AnthonyGiretti — APPROVED** [review]
great thank you!

MIP! (merge in peace)

**Comment by AllanTee** [comment]
Hi, 
Please describe more specifically for beginner in Angular, how and where to exactly complete these commands:

1. 
CREATE DATABASE SignalRDemo;

2. 
USE [SignalRDemo]
GO

3. 
/****** Object:  Table [dbo].[GaugesData]    Script Date: 2017-12-30 14:51:37 ******/
SET ANSI_NULLS ON
GO

4. 
SET QUOTED_IDENTIFIER ON
GO

5. 
CREATE TABLE [dbo].[GaugesData](
	[Id] [int] NOT NULL,
	[Memory] [int] NOT NULL,
	[Cpu] [int] NOT NULL,
	[Network] [int] NOT NULL,
 CONSTRAINT [PK_GaugesData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

6. 
ALTER DATABASE SignalRDemo SET ENABLE_BROKER with rollback immediate


I managed to complete only the first and the fifth command, so now I have a database and table  in local SQL Server of Visual Studio 2017 ver. 15.5.3.

I'm getting following error:
FileLoadException: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
TableDependency.SqlClient.SqlTableDependency.CheckIfConnectionStringIsValid(string connectionString)

Allan

**Comment by AnthonyGiretti** [comment]
Hi!

Thank you for your feedback.
I appreciate it.

I added some comments for the setup :
"

For an easy setup with SQL SERVER, I recommand to use LocalDB, installed
automatically since Visual Studio 2012

Use for example SQL Management Studio V12+ top type this serie of commands:
"

Would you mind tell me what verison of .NET Core you are using? Which
version of SqlTableDependency did you use? there are 6.0 anfd 6.1.
Please try to add  System.Data.SqlClient manually, normally EF install it.


Thank you!

2018-02-03 12:55 GMT-05:00 AllanTee <notifications@github.com>:

**Comment by AllanTee** [comment]
Hi,

I have following packages installed:
Microsoft.AspNetCore.All" Version="2.0.3"
Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final"
Microsoft.EntityFrameworkCore" Version="2.0.1"
Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1"
SqlTableDependency" Version="6.1.0"
System.Data.SqlClient" Version="4.4.2".

Installed the SQL Management Studio 2017. Didn't work. Too heavy thing, Uninstalled it. 
Now trying with Database .NET manager, not success so far. It connects perfectly to my external MySQL databases, but not to MSSQL Local database, which I created yesterday (I created it in Visual Studio SQL Server Design Window).
When trying to launch the project in Visual Studio, still getting the database connection errors. I even changed the connection string provided in the project with the real connection string, which I got from connection properties window. Still connection errors?

Please, can you provide a straightforward method to create the database and the table using simple syntax, which can be run in the Visual Studio 2017 Designer window.

**Comment by AnthonyGiretti** [comment]
You have to install sql management studio , it should not fail.
You don’t need to install everything, just the editor .
Try to follow a tutorial to install it. It will work.

Else I can suggest you to make your sql via visual studio with
https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/sql-editor-visual-database-tools

Good luck!

**Comment by AllanTee** [comment]
Hi,

Installed SQL Server Data Tools For Visual Studio 2017. Database commands were executed successfully.

Visual Studio Output is:

1>------ Rebuild All started: Project: SignalrCoreDemoWithSqlTableDependency, Configuration: Debug Any CPU ------

1>C:\Users\A\Documents\Visual Studio 2017\Projects\Angular5-RealTime-gauges-with-SignalR-Core-EFCore2-master\BackEnd\SignalrCoreDemoWithSqlTableDependency\SignalrCoreDemoWithSqlTableDependency.csproj : warning NU1701: Package 'SqlTableDependency 6.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

1>SignalrCoreDemoWithSqlTableDependency -> C:\Users\A\Documents\Visual Studio 2017\Projects\Angular5-RealTime-gauges-with-SignalR-Core-EFCore2-master\BackEnd\SignalrCoreDemoWithSqlTableDependency\bin\Debug\netcoreapp2.0\SignalrCoreDemoWithSqlTableDependency.dll

1>Done building project "SignalrCoreDemoWithSqlTableDependency.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Error List is clear. But I got following error: on the browser:
TableDependency.SqlClient.SqlTableDependency.CheckIfUserHasPermissions(string connectionString)

I changed initial catalog of the connection string from "master" to "SignalRDemo".

ConnectionString = @"Data Source = (localdb)\MSSQLLocalDB;Initial Catalog = SignalRDemo; Integrated Security = True; Connect Timeout = 30; Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;";

Visual Studio output remains the same. Now the browser produces a small text "Hello World!" on the white screen. No charts?

**Comment by AnthonyGiretti** [comment]
Launch the angular web app.
.net is only the back end

**Comment by AllanTee** [comment]
Hi Anthony,

I have learned now, how to launch Angular apps, but new problems arise:

C:\Users\A\Documents\Visual Studio 2017\Projects\Angular5-RealTime-gauges-with-SignalR-Core-EFCore2-master\BackEnd>ng serve
module.js:540
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\A\Documents\Visual Studio 2017\Projects\Angular5-RealTime-gauges-with-SignalR-Core-EFCore2-master\BackEnd\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3).

**Comment by AnthonyGiretti** [comment]
MAKE properly npm install in the project

**Pull request merged**
